const homeApi = {
	queryMyOrders:"/trade/customer/queryMyOrders",  //獲取訂單列表
	addCart:"/trade/cart/addCart",	//添加购物车
	getCarts:"/trade/cart/getCarts",	//获取购物车列表
	editCart:"/trade/cart/editCart",	//修改购物车信息
	moveToFavorite:"/trade/cart/moveToFavorite/",	//移入收藏夹
	removeCarts:"/trade/cart/removeCarts",	//清空失效商品
	moveToFavorites:"/trade/cart/moveToFavorites",	//批量
	evaluateGoods:"/trade/customer/evaluateGoods/",	//获取评价商品
	appendEvaluate:"/trade/customer/evaluateGoods/append/",		//追评详情
	pageInit:"/trade/order/pageInit",		//初始化结算
	storePromotions:"/trade/order/storePromotions",	//获取店铺促销信息
	storeCoupons:"/trade/order/storeCoupons",	//获取店铺优惠券信息
	freightPromotions:"/trade/order/freightPromotions",	//获取店铺包邮活动信息
	storeOrderAmount:"/trade/order/storeOrderAmount",	//获取店铺订单金额
	platformPromotions:"/trade/order/platformPromotions",	//获取平台优惠券信息
	orderGold:"/trade/order/orderGold",	//获取权益金
	orderScore:"trade/order/orderScore",	//获取积分信息
	orderSummary:"/trade/order/orderSummary",	//获取总订单价格
	submitOrder:"/trade/order/submitOrder",		//提交订单
	deleteOrder:"/trade/customer/deleteOrder/",	//删除订单
	getCustomerRefundOrderPage:"trade/refund/customer/getCustomerRefundOrderPage",	//获取售后列表
	refundDetail:"/trade/refund/customer/refundDetail/",	//售后详情
	queryOrderDetail:"/trade/customer/queryOrderDetail/",	//查询订单详情
	cancelOrder:"/trade/customer/cancel/",	//取消订单
	applyFofRefund:"/trade/refund/customer/applyFofRefund",	//售后详情
	refundReason:"/trade/refund/customer/refundReason/",	//售后原因
	submitApplyFofRefund:"/trade/refund/customer/submitApplyFofRefund",	//提交售后
	extendShip:"/trade/customer/extendShip/",	//延长收货
	confirmReceipt:"/trade/customer/confirmReceipt/",	//确认售后
	queryMyUnCommentOrders:"/trade/customer/queryMyUnCommentOrders",	//评价成功页面调用
	cancelTrade:"/trade/refund/customer/cancel/",	//取消申请售后
	platformInvolve:"/trade/refund/customer/platformInvolve/",	//申诉
	summary:"/trade/pay/summary/",	//收银台详情
	submitPay:"/trade/pay/submit",	//提交支付
	defaultCards:"/trade/pay/defaultCards",	//根据用户更改支付类型判断礼卡可用余额
	selectCards:"/trade/pay/selectCards",	//收银台礼卡更改时触发
	sendOrderSms:"/trade/order/sendOrderSms",	//发送验证码
	sendSMS:"/trade/pay/sendSMS/",	//收银台发送验证码
	submitLogisticsInfo:"/trade/refund/customer/submitLogisticsInfo",	//寄回商品
	tradeFirstOrder:"/trade/customer/firstOrder/",	//判断是否为新用户首单
	validSubmitCarts:"/trade/cart/validSubmitCarts",	//购物车结算校验
	cusPageInit:"/trade/customize/order/pageInit",	//定制品下单初始化
	submitCusOrder:"/trade/customize/order/submitOrder",	//定制品提交订单
	buildPayOrder:"/trade/customize/order/buildPayOrder",	//构建支付订单
	submitPayOrder:"/trade/customize/order/submitPayOrder",	//提交线下支付订单
	getCompanyPaymentInfo:"/trade/customize/order/getCompanyPaymentInfo",	//获取公司对公账号信息
	listPayLog:"/trade/customize/order/listPayLog/",	//获取订单的支付记录
	listOrderPage:"/trade/customize/order/listOrderPage",	//查询定制订单列表
	getOrderInfo:"/trade/customize/order/getOrderInfo/",	//获取定制订单详情
	cancelCusOrder:"/trade/customize/order/cancelOrder/",	//取消定制订单
	giftBagPageInit:"/trade/giftBagTransfer/order/pageInit",	//转增商品下单初始化
	giftBagGoldOrder:"/trade/giftBagTransfer/order/goldOrder",	//购物金可使用情况
	giftBagScoreOrder:"/trade/giftBagTransfer/order/scoreOrder",	//积分可使用情况
	giftBagSummaryOrder:"/trade/giftBagTransfer/order/summaryOrder",	//计算订单需要支付情况
	giftBagSubmitOrder:"/trade/giftBagTransfer/order/submitOrder",	//提交订单
	giftBagPageOrders:"/trade/giftBagTransfer/order/pageOrders",	//我的礼包列表
	giftBagPageGetLogs:"/trade/giftBagTransfer/order/pageGetLogs",	//转赠单领取记录
	giftBagCancelOrder:"/trade/giftBagTransfer/order/cancelOrder",	//取消订单
	giftBagGeneratePoster:"/trade/giftBagTransfer/order/generatePoster/",	//生成转赠海报
	giftBagInfo:"/trade/giftBagTransfer/order/giftBagInfo/",	//转增单详情
}
export default homeApi;
